### ISSUE TITLE
Graphs default location: Newcastle

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-gba-housing-affordability#15]
Please make Newcastle the default location for all graphs within build.

Dropdown to list all alphabetically

**Comment by antharca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Housing affordability long form - dev](https://trello.com/c/v3d527qy/3-housing-affordability-long-form-dev)

**Comment by thiagodebastos** [comment]
@antharca is this really necessary? I'm going to leave this in the feature backlog as it adds more logic to the widgets and will take time I don't really have at the moment.
