### ISSUE TITLE
Remove White bar below top header

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-gba-housing-affordability#17]
OSX - Chrome/Safari/FF
![greaterbank](https://user-images.githubusercontent.com/25311536/31105019-a09c21ca-a82c-11e7-9a5f-1a580065df27.jpg)

**Comment by thiagodebastos** [comment]
@antharca can you please help me replicate this? 
What browser versions are you using, and did you do anything in specific. I'm having trouble replicating this issue. Maybe I accidentally fixed it when I updated the video header.

**Comment by antharca** [comment]
Chrome 60, OSX
Just loaded the page and this appeared.

Have a new screenshot after the video header was put into it (attached)
![atom template - revision](https://user-images.githubusercontent.com/25311536/31473833-ad083b52-af42-11e7-81a1-93eb2546c738.jpg)

**Comment by thiagodebastos** [comment]
Ok, I think it must be coming from Composer styles, I'll test it within the Guardian 'iFrame' and get back to you!
