### ISSUE TITLE
Copy update - first paragragh

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-gba-housing-affordability#2]
First paragraph
- update 

"Yes, we aware" 

to 

"Yes, we're aware"

**Comment by antharca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Housing affordability long form - dev](https://trello.com/c/v3d527qy/3-housing-affordability-long-form-dev)

**Comment by thiagodebastos** [comment]
@antharca how do I create an issue for misspelling 'paragraph' in this issue's title? haha

**Comment by antharca** [comment]
Issue-ception
